version: "3"
volumes:
  db-store:
services:
  builder:
    env_file: ./.env
    tty: true
    volumes:
      - type: bind
        source: ./backend/${HOST_BACKEND_SRC_PATH:-src/spring-boot-demo}
        target: "/work/maven"
      - type: bind
        source: ${M2_DIR:-~/.m2}
        target: "/home/webapp/.m2"
    build:
      context: ./backend
      dockerfile: ./builder/Dockerfile
      args:
        OWNER_USER_ID: ${OWNER_USER_ID}
        OWNER_GROUP_ID: ${OWNER_USER_ID}
  
  tomcat:
    tty: true
    ports:
      - 8080:8080
    build:
      context: ./backend
      dockerfile: ./tomcat/Dockerfile
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-spring_local}
      - DB_USERNAME=${DB_USER:-javarista}
      - DB_PASSWORD=${DB_PASS:-secret}
  
  db:
    build:
      context: ./backend
      dockerfile: ./db/mysql/Dockerfile
    ports:
      - ${DB_EXT_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-spring_local}
      - MYSQL_USER=${DB_USER:-javarista}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
